load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "loginBean",
    srcs = ["LoginBean.java"],
    main_class = "net.javaguides.todoapp.model.LoginBean",
    visibility = ["//src/net/javaguides/todoapp/dao:__pkg__","//src/net/javaguides/todoapp/controller:__pkg__"],
    
    
)
